"""
generate_hls.py — Step 5: Emit Vitis HLS C++ for both baseline and hybrid designs.

Per experiment, per class, writes:
  hls_generated/{exp}/class_{j}/symbolic_layer.cpp
  hls_generated/{exp}/class_{j}/symbolic_layer.h
  hls_generated/{exp}/class_{j}/synth.tcl

Also writes the full baseline MLP HLS under hls_generated/baseline/.

Sparse scalar interface:  only variables that actually appear in the expression
are declared as function parameters → zero dead ports in the synthesised RTL.
"""
from __future__ import annotations
import argparse
import ast
import json
import re
from pathlib import Path

import config

# ─── Expression → C float string ─────────────────────────────────────────────

_RENAME_FN = {"sin": "sinf", "cos": "cosf", "exp": "expf",
              "sqrt": "sqrtf", "log": "logf", "abs": "fabsf"}


class _CppTransformer(ast.NodeTransformer):

    def visit_BinOp(self, node):
        self.generic_visit(node)
        if isinstance(node.op, ast.Pow):
            lhs, rhs = ast.unparse(node.left), ast.unparse(node.right)
            stub = f"_square({lhs})" if rhs == "2" else f"powf({lhs}, {rhs})"
            return ast.parse(stub, mode="eval").body
        if isinstance(node.op, ast.Div):
            lhs, rhs = ast.unparse(node.left), ast.unparse(node.right)
            return ast.parse(f"_safe_div({lhs}, {rhs})", mode="eval").body
        return node

    def visit_Call(self, node):
        self.generic_visit(node)
        if isinstance(node.func, ast.Name):
            node.func.id = _RENAME_FN.get(node.func.id, node.func.id)
        return node

    def visit_Constant(self, node):
        if isinstance(node.value, (int, float)):
            return ast.parse(f"{float(node.value)!r}f", mode="eval").body
        return node


def _to_cpp(expr: str) -> str:
    """PySR expression → C float expression (xN → x_N, Python ops → C ops)."""
    expr = re.sub(r"\bx(\d+)\b", r"x_\1", expr)
    try:
        tree = ast.parse(expr, mode="eval")
        tree = _CppTransformer().visit(tree)
        ast.fix_missing_locations(tree)
        expr = ast.unparse(tree.body)
    except Exception:
        pass
    # Bare float literals without 'f' suffix
    expr = re.sub(r"(?<!['\w])(\d+\.\d+)(?!f|\d)", r"\1f", expr)
    return expr


def _used_indices(cpp_expr: str) -> list[int]:
    return sorted(set(int(m) for m in re.findall(r"\bx_(\d+)\b", cpp_expr)))


def _params(used: list[int]) -> str:
    return ", ".join(f"float x_{i}" for i in used) if used else "float x_0"


# ─── HLS file templates ───────────────────────────────────────────────────────

_CPP_T = """\
#include "symbolic_layer.h"
#include <cmath>

static inline float _square(float x) {{ return x * x; }}
static inline float _safe_div(float a, float b) {{
    return (fabsf(b) < 1e-8f) ? 0.0f : a / b;
}}

/* Symbolic logit for class {cls}  |  exp={exp}  layer={layer}  ops={op_set}
   Original PySR equation: {raw_eq} */
float symbolic_class_{cls}({params}) {{
#pragma HLS INLINE off
    return {expr};
}}
"""

_H_T = """\
#pragma once
/* Class {cls} symbolic logit — generated by NeuHLS (MNIST 784→128→64→10) */
float symbolic_class_{cls}({params});
"""

_TCL_T = """\
open_project -reset sym_cls_{cls}
set_top symbolic_class_{cls}
add_files symbolic_layer.cpp
open_solution -reset sol1
set_part {{xc7a35tcpg236-1}}
create_clock -period 10 -name default
csynth_design
export_design -rtl verilog -format ip_catalog
close_project
"""


def _generate_for_experiment(exp_name: str):
    eq_path = config.EQ_DIR / exp_name / "equations.json"
    if not eq_path.exists():
        print(f"[{exp_name}] equations.json missing — skipping.")
        return

    with open(eq_path) as f:
        eq_data = json.load(f)

    layer  = config.get_layer(exp_name)
    op_set = config.get_op_set(exp_name)
    exp_dir = config.HLS_GEN_DIR / exp_name

    for entry in sorted(eq_data["classes"], key=lambda e: e["class"]):
        cls      = entry["class"]
        raw_eq   = entry["equation"]
        cpp_expr = _to_cpp(raw_eq)
        used     = _used_indices(cpp_expr) or [0]
        params   = _params(used)

        cls_dir = exp_dir / f"class_{cls}"
        cls_dir.mkdir(parents=True, exist_ok=True)

        (cls_dir / "symbolic_layer.cpp").write_text(
            _CPP_T.format(cls=cls, exp=exp_name, layer=layer, op_set=op_set,
                          raw_eq=raw_eq, params=params, expr=cpp_expr))
        (cls_dir / "symbolic_layer.h").write_text(
            _H_T.format(cls=cls, params=params))
        (cls_dir / "synth.tcl").write_text(
            _TCL_T.format(cls=cls))
        print(f"  [{exp_name}] class {cls}  vars={used}  expr={cpp_expr[:55]}…")

    print(f"HLS written → {exp_dir}\n")


def _generate_baseline_hls():
    """Emit parameterised MLP HLS C++ for Vitis synthesis comparison."""
    D, H1, H2, C = config.INPUT_DIM, config.H1_DIM, config.H2_DIM, config.NUM_CLASSES
    out_dir = config.HLS_GEN_DIR / "baseline"
    out_dir.mkdir(parents=True, exist_ok=True)

    cpp = f"""\
#include "baseline_mlp.h"
#include <cmath>

static inline float relu(float x) {{ return x > 0.0f ? x : 0.0f; }}

/* Baseline MLP: {D} → {H1} → {H2} → {C}
   Weights passed as arguments; bind to BRAMs via #pragma HLS BIND_STORAGE. */
void baseline_mlp(
    float x[{D}], float out[{C}],
    const float w1[{D}][{H1}], const float b1[{H1}],
    const float w2[{H1}][{H2}], const float b2[{H2}],
    const float w3[{H2}][{C}],  const float b3[{C}]
) {{
#pragma HLS PIPELINE II=1
    float h1[{H1}], h2[{H2}];

    FC1: for (int j = 0; j < {H1}; j++) {{
#pragma HLS UNROLL factor=4
        float acc = b1[j];
        for (int i = 0; i < {D}; i++) acc += x[i] * w1[i][j];
        h1[j] = relu(acc);
    }}
    FC2: for (int j = 0; j < {H2}; j++) {{
#pragma HLS UNROLL factor=4
        float acc = b2[j];
        for (int i = 0; i < {H1}; i++) acc += h1[i] * w2[i][j];
        h2[j] = relu(acc);
    }}
    FC3: for (int j = 0; j < {C}; j++) {{
        float acc = b3[j];
        for (int i = 0; i < {H2}; i++) acc += h2[i] * w3[i][j];
        out[j] = acc;
    }}
}}
"""
    h = f"""\
#pragma once
void baseline_mlp(
    float x[{D}], float out[{C}],
    const float w1[{D}][{H1}], const float b1[{H1}],
    const float w2[{H1}][{H2}], const float b2[{H2}],
    const float w3[{H2}][{C}],  const float b3[{C}]
);
"""
    tcl = f"""\
open_project -reset baseline_mlp
set_top baseline_mlp
add_files baseline_mlp.cpp
open_solution -reset sol1
set_part {{xc7a35tcpg236-1}}
create_clock -period 10 -name default
csynth_design
export_design -rtl verilog -format ip_catalog
close_project
"""
    (out_dir / "baseline_mlp.cpp").write_text(cpp)
    (out_dir / "baseline_mlp.h").write_text(h)
    (out_dir / "synth.tcl").write_text(tcl)
    print(f"Baseline HLS written → {out_dir}")


def parse_args():
    p = argparse.ArgumentParser(description="Generate Vitis HLS C++ code")
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--experiment", type=str, choices=config.EXPERIMENTS)
    g.add_argument("--all",        action="store_true",
                   help="Generate HLS for all experiments")
    g.add_argument("--baseline",   action="store_true",
                   help="Generate baseline MLP HLS only")
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    if args.baseline:
        _generate_baseline_hls()
    else:
        exps = config.EXPERIMENTS if args.all else [args.experiment]
        _generate_baseline_hls()
        for exp in exps:
            _generate_for_experiment(exp)
