// mlp_top.cpp
// NeuSym-HLS — full MNIST hybrid network.
//   x[784] --fc1--> h1[128] --ReLU--> --fc2--> h2[64] --ReLU--> symbolic_head --> logits[10]
//
// fc1/fc2: quantized fixed-point matrix-vector products (use DSPs).
// fc3    : the shift-add symbolic head from symbolic_head.cpp (0 DSP).
//
// Weights are compile-time ROMs generated by export_weights.py:
//   W1[H1_DIM][IN_DIM], B1[H1_DIM], W2[H2_DIM][H1_DIM], B2[H2_DIM]

#include "mlp.h"
#include "fc1_params.h"   // generated: W1, B1
#include "fc2_params.h"   // generated: W2, B2

// parallelism knobs (tune for area/latency)
// UNROLL_F1/F2 must divide IN_DIM/H1_DIM. Start at 1 (smallest area), raise to
// trade LUT/DSP for latency. Keep the matching ARRAY_PARTITION factors in sync.
#define UNROLL_F1 1
#define UNROLL_F2 1

static inline feat_t relu(macc_t a) {
#pragma HLS INLINE
    return (a > (macc_t)0) ? (feat_t)a : (feat_t)0;
}

void mlp_top(const feat_t x[IN_DIM], logit_t logits[N_CLS]) {
#pragma HLS INTERFACE ap_memory port=x
#pragma HLS INTERFACE ap_memory port=logits
#pragma HLS INTERFACE ap_ctrl_hs port=return

    feat_t h1[H1_DIM];
    feat_t h2[H2_DIM];
#pragma HLS ARRAY_PARTITION variable=h2 complete dim=1   // symbolic head wants this

    //  fc1: 784 -> 128, ReLU
    FC1_OUT: for (int o = 0; o < H1_DIM; o++) {
        macc_t acc = (macc_t)B1[o];
        FC1_IN: for (int i = 0; i < IN_DIM; i++) {
#pragma HLS PIPELINE II=1
#pragma HLS UNROLL factor=UNROLL_F1
            acc += (macc_t)(W1[o][i] * x[i]);
        }
        h1[o] = relu(acc);
    }

    //  fc2: 128 -> 64, ReLU 
    FC2_OUT: for (int o = 0; o < H2_DIM; o++) {
        macc_t acc = (macc_t)B2[o];
        FC2_IN: for (int j = 0; j < H1_DIM; j++) {
#pragma HLS PIPELINE II=1
#pragma HLS UNROLL factor=UNROLL_F2
            acc += (macc_t)(W2[o][j] * h1[j]);
        }
        h2[o] = relu(acc);
    }

    // fc3: symbolic head (64 -> 10) 
    symbolic_head(h2, logits);
}
